# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://wanglilab.github.io/'
baseurl: ''
title: 'WangLi Lab'
description: 'Evolutionary genomics of crops and Chinese herbs'
permalink: pretty
logo: 

# Pagination
paginate: 5
paginate_path: news/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: Research
  url: /research/
- title: Publications
  url: /publications/
- title: People
  url: /people/
- title: News
  url: /news/
- title: Teaching
  url: /teaching/
- title: Journal Club
  url: /Journal Club/
# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    output: true
    description: "<b>Notable events in the Wang Lab</b>"
    feature_text: |
      ## <span style="color:white">News</span>
    feature_image: "https://WangLiLab.github.io/picture/Homepage.png"
